In [25]:
import numpy as np

#Q#1: Create x array with elements equal to 1.

x = np.zeros((1,1))

#Q#2: Create y array with elements equal to 0.

y =np.ones((1,1))

#Q#3: Add x and y arrays.

a=x+y

#Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

print('type = ', x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)

#Q#5: Create a 2D array "called w" as the following:

w = np.array([[11, 12], [13, 14],[15,16]])

#Q#6: Create z array contains the numbers from 1 to 3.

z = np.arange(1,4).reshape((3, 1))
 
#Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".


newArray=np.append(w,z, axis=1)

print(newArray)
 
#Q#8: Print all elements of "newArray" using the loop.
for row in newArray:
    for item in row:
        print(item)
  

#Q#9: Reverse the columns and rows of "newArray".


RnewArray=newArray.transpose()
print(RnewArray)
 
    
#Q#11: Find smallest and biggest values in "newArray".

print(RnewArray.min())
print(RnewArray.max())

#Q#12: Print the first row of "newArray" using indexing.

print(newArray[0]) 

#Q#13: Print the number equals 12 of "newArray" using indexing.

print(newArray[0, 1])


#Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

 
for v in newArray[1,:]:
    if v== 13 or v==0:
        print(v)

#Q#15: Change the shape of "newArray" to (9,1).
 
print(newArray.reshape(9,1))

#Q#16: Change the shape of "newArray" to (3,2).
 
#newArray.reshape(3,2)
 

type =  float64
number of dimensions =  2
shape =  (1, 1)
size =  1
[[11 12  1]
 [13 14  2]
 [15 16  3]]
11
12
1
13
14
2
15
16
3
[[11 13 15]
 [12 14 16]
 [ 1  2  3]]
1
16
[11 12  1]
12
13
shape =  (3, 3)
[[11]
 [12]
 [ 1]
 [13]
 [14]
 [ 2]
 [15]
 [16]
 [ 3]]
shape =  (3, 3)
