In [5]:
import numpy as np

In [11]:
x = np.ones((3, 3))
y = np.zeros((3, 3))

In [12]:
c = x+y
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
x.dtype

dtype('float64')

In [14]:
c.ndim

2

In [15]:
x.size

9

In [16]:
x.shape

(3, 3)

In [33]:
w = np.array([[11,13,15],[12,14,16]])
print(w)

[[11 13 15]
 [12 14 16]]


In [27]:
z = np.array([1,2,3])

In [32]:
new_array = np.vstack((w,z)) 
print(new_array)

[[11 13 15]
 [12 14 16]
 [ 1  2  3]]


In [34]:
new_array.shape

(3, 3)

In [35]:
for a in new_array:
    print(a)

[11 13 15]
[12 14 16]
[1 2 3]


In [36]:
new_array_T = new_array.T
print (new_array_T)

[[11 12  1]
 [13 14  2]
 [15 16  3]]


In [37]:
Minus_array = new_array -1
print (Minus_array)

[[10 12 14]
 [11 13 15]
 [ 0  1  2]]


In [38]:
min_array = new_array.min()
print (min_array)

1


In [43]:
first_row = new_array[0]
print (first_row)

[11 13 15]


In [48]:
twelve = new_array[1,0]
print(twelve)

12


In [50]:
print (new_array[0, 1:2])

[13]


In [52]:
newer_array = new_array.reshape(9,1)
print (newer_array)


[[11]
 [13]
 [15]
 [12]
 [14]
 [16]
 [ 1]
 [ 2]
 [ 3]]


In [53]:
newer2_array = new_array.reshape(3,2)
print(newer2_array)

ValueError: cannot reshape array of size 9 into shape (3,2)