In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
x = np.ones(2)

## Q#2: Create y array with elements equal to 0.

In [4]:
y = np.zeros(2)

## Q#3: Add x and y arrays.

In [5]:
np.add(x,y)

array([1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [7]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

1
(2,)
2
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [10]:
w = np.arange(11,17).reshape(3,2)
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [30]:
z = np.arange(1,4).reshape(1,3)
z

array([[1, 2, 3]])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [36]:
newArray = np.concatenate((w, z.T), axis=1)
newArray

array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [43]:
for i in newArray:
    for j in i:
        print(j)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [50]:
newArray = newArray.T

newArray

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [55]:
newArray -= 1
newArray

array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [58]:
bigest = np.max(newArray)
smallest = np.min(newArray)

bigest

15

## Q#12: Print the first row of "newArray" using indexing.

In [59]:
newArray[0,:]

array([10, 12, 14])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [60]:
newArray[0,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [91]:
for i in newArray.flat[4:7:2]:
   print(i)


13
0


## Q#15: Change the shape of "newArray" to (9,1).

In [67]:
newArray.reshape(9,1)

array([[10],
       [12],
       [14],
       [11],
       [13],
       [15],
       [ 0],
       [ 1],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [94]:
#ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉