In [122]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [123]:
x = np.ones(3 , dtype = int )
x

array([1, 1, 1])

## Q#2: Create y array with elements equal to 0.

In [124]:
y = np.zeros(3 , dtype = int)
y

array([0, 0, 0])

## Q#3: Add x and y arrays.

In [125]:
z = sum(x,y)
z

array([3, 3, 3])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [126]:
x.shape 

(3,)

In [127]:
x.dtype 

dtype('int32')

In [128]:
x.ndim

1

In [129]:
x.size

3

In [130]:
x.data

In [131]:
x.itemsize

4

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [132]:
w =  np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [133]:
z = np.array([1,2,3])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [134]:
newArray = np.column_stack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [135]:
for item in newArray.flat:
    print(item)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [136]:
#np.fliplr(newArray)

In [137]:
#np.flipud(newArray)

In [138]:
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [139]:
newArray -= 1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [140]:
newArray.max()

15

In [141]:
newArray.min()

0

## Q#12: Print the first row of "newArray" using indexing.

In [142]:
print(newArray[0])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [143]:
print(newArray[1,1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [144]:
newArray[1:6:5]

array([[ 1, 12, 13]])

## Q#15: Change the shape of "newArray" to (9,1).

In [145]:
newArray.reshape((9,1))

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [121]:
newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉