In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
x=np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [4]:
y=np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [5]:
z=np.add(x,y)
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [6]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

2
(3, 3)
9
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [7]:
w=np.arange(11,17)
w=w.reshape(3,2)


## Q#6: Create z array contains the numbers from 1 to 3.

In [8]:
z=np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [9]:
z=z.reshape(3,1)
newarray=np.concatenate((w,z),axis=1)
print(newarray)


[[11 12  1]
 [13 14  2]
 [15 16  3]]


## Q#8: Print all elements of "newArray" using the loop.

In [10]:
for n in newarray:
    print(n)

[11 12  1]
[13 14  2]
[15 16  3]


## Q#9: Reverse the columns and rows of "newArray".

In [11]:
newarray=newarray.T

## Q#10: Decrement all elements of "newArray" with 1.

In [12]:
newarray-=1
newarray

array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [13]:
print(newarray.min())
print(newarray.max())

0
15


## Q#12: Print the first row of "newArray" using indexing.

In [14]:
print(newarray[0:1])

[[10 12 14]]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [15]:
print(newarray[0,1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [31]:
print(newarray[1,1],newarray[2,0])


13 0


## Q#15: Change the shape of "newArray" to (9,1).

In [32]:
newarray.reshape(9,1)

array([[10],
       [12],
       [14],
       [11],
       [13],
       [15],
       [ 0],
       [ 1],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [35]:
#Can't convert there are more elements that indices

array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

# Well Done 🎉