In [24]:
import numpy as np
import pandas as pd

## Q#1: Create x array with elements equal to 1.

In [6]:
x=np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [7]:
y= np.zeros((2, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [9]:
a= x+y
a

array([[1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [10]:
print(x.size)
print(x.shape)
print(x.dtype)
print(x.itemsize)
print(x.ndim)
print(x.data)

6
(2, 3)
float64
8
2


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [11]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [14]:
z= np.arange(3)
z

array([0, 1, 2])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [21]:
h= np.column_stack((w, z))
h

array([[11, 12,  0],
       [13, 14,  1],
       [15, 16,  2]])

## Q#8: Print all elements of "newArray" using the loop.

In [22]:
for i in h:
    print(i)

[11 12  0]
[13 14  1]
[15 16  2]


## Q#9: Reverse the columns and rows of "newArray".

In [27]:
print(h.transpose())

[[11 13 15]
 [12 14 16]
 [ 0  1  2]]


## Q#10: Decrement all elements of "newArray" with 1.

In [39]:
h-=1

h

array([[ 8,  9, -3],
       [10, 11, -2],
       [12, 13, -1]])

## Q#11: Find smallest and biggest values in "newArray".

In [40]:
h.min()

-3

In [41]:
h.max()

13

## Q#12: Print the first row of "newArray" using indexing.

In [50]:
print (h[0])

[ 8  9 -3]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [52]:
print (h[2,0])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [55]:
print (h[:0:9])

[]


## Q#15: Change the shape of "newArray" to (9,1).

In [57]:
q = h.reshape([9,1])
q

array([[ 8],
       [ 9],
       [-3],
       [10],
       [11],
       [-2],
       [12],
       [13],
       [-1]])

## Q#16: Change the shape of "newArray" to (3,2).

In [63]:
ee= np.reshape(q,[3,2])

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉