In [12]:
#1: Create x array with elements equal to 1.
import numpy as np
x=np.ones((3,3),dtype=int)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
#2: Create y array with elements equal to 0.
y=np.zeros((3,3),dtype=int)
print(y)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [29]:
#4 Print x array characteristics (e.g: dimension, shape, size, type)


x= np.array([[1,2,3],[4,5,6]])
print('items size:', x.size)

x.ndim
x.shape

items size: 6


(2, 3)

In [67]:
#5: Create a 2D array "called w" as the following:
w= np.array([[11,12],[13,14],[15,16]])
print(w)


[[11 12]
 [13 14]
 [15 16]]


2

In [72]:

#6: Create z array contains the numbers from 1 to 3.

z=np.arange(1,4)
print(z)
z.reshape(3, 1)

[1 2 3]


array([[1],
       [2],
       [3]])

In [76]:
#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".
newArray=np.column_stack((z, w))


[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


In [77]:
#8: Print all elements of "newArray" using the loop.
for row in newArray :
    for item in row:
        print(item)

1
11
12
2
13
14
3
15
16


In [113]:
#9 Reverse the columns and rows of "newArray"
np.transpose(newArray)


array([9])

In [81]:
#10: Decrement all elements of "newArray" with 1.
np.subtract(newArray,1)

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

In [85]:
#11: Find smallest and biggest values in "newArray".
newArray.min()
newArray.max()

16

In [93]:
#12: Print the first row of "newArray" using indexing.
print(newArray[0])

[ 1 11 12]


In [95]:
#13: Print the number equals 12 of "newArray" using indexing.
print(newArray[0,2])

12


In [110]:
#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.
print(newArray[np.where((newArray == 13) | (newArray == 0))])

[]


In [107]:
#15: Change the shape of "newArray" to (9,1)
newArray=np.reshape(9,1)



[9]


In [104]:
#16: Change the shape of "newArray" to (3,2).
'Eroor